# Настройки валюты
currency: "money"

# Миры, где разрешён полёт
worlds:
  - "world"

# Перезарядка после использования полёта (в миллисекундах)
cooldown: 600000

# Уровни полёта
flight-tiers:
  1:
    cost: 50000
    duration: 120
  2:
    cost: 100000
    duration: 300
  3:
    cost: 200000
    duration: 600

# Скорости полёта (значения от 0.0 до 1.0)
fly-speeds:
  1: 0.1
  2: 0.2
  3: 0.4
